version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MY_SQL_PASSWORD:
      MY_SQL_DB: laravel
    volumes:
      - "./.docker/dbdata:/var/lib/mysql/data"
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web